config/routes.rb
Technobabble::Application.routes.draw do
  resources :terms do
    resources :definitions
  end

  resources :users
  resources :definitions
  resources :groups

  match '/' => 'main#home'

  match 'search' => 'terms#search', :as => :search

  match 'admin' => 'main#admin'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  belongs_to :term
  belongs_to :group
  attr_accessible :content, :group_id

  validates_presence_of :content

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :definitions

  attr_accessible :name, :users_attributes, :definitions_attributes
  accepts_nested_attributes_for :definitions, :allow_destroy => true
end

app/models/term.rb
class Term < ActiveRecord::Base
  has_many :definitions#, :dependent => :destory

  accepts_nested_attributes_for :definitions, :allow_destroy => true
  attr_accessible :name, :tags, :definitions_attributes

  validates :name, :presence => true, :uniqueness => true

  def self.search(query)
    if query
      formated_query = '%' + query + '%'
      find(:all, :conditions => ['name LIKE ? OR tags LIKE ?', formated_query, formated_query])
    else
      find :all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :group

  attr_accessible :username

  validates :username, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  http_basic_authenticate_with :name => "admin", :password => "admin", :only => :admin
  # GET /
  # Homepage - google-esque search box
  def home
    respond_to do |format|
      format.html #home.erb.html 
    end
  end

  def admin
    @terms = Term.all
    @definitions = Definition.all
    @groups = Group.all
    @users = User.all

    respond_to do |format|
      format.html #admin.erb.html
    end
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  # GET /terms
  # GET /terms.json
  def index
    @terms = Term.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @terms }
    end
  end

  # GET /terms/1
  # GET /terms/1.json
  def show
    @term = Term.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/new
  # GET /terms/new.json
  def new
    @term = Term.new
    @term.definitions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @term }
    end
  end

  # GET /terms/1/edit
  def edit
    @term = Term.find(params[:id])
    @term.definitions.build
  end

  # POST /terms
  # POST /terms.json
  def create
    @term = Term.new(params[:term])

    respond_to do |format|
      if @term.save
        format.html { redirect_to @term, notice: 'Term was successfully created.' }
        format.json { render json: @term, status: :created, location: @term }
      else
        format.html { render action: "new" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /terms/1
  # PUT /terms/1.json
  def update
    @term = Term.find(params[:id])

    respond_to do |format|
      if @term.update_attributes(params[:term])
        format.html { redirect_to @term, notice: 'Term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /terms/1
  # DELETE /terms/1.json
  def destroy
    @term = Term.find(params[:id])
    @term.destroy

    respond_to do |format|
      format.html { redirect_to terms_url }
      format.json { head :no_content }
    end
  end

  # Search term names
  def search
    @terms = Term.search params[:q] 
    
    respond_to do |format|
      format.html #search.html.erb
      format.json { render json: @terms }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technobabble</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/_term.html.erb
<! --
<tr>
  <div class="field">
    <%= form_for term do |f| %>
      <td class="name">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </td>
      <%= f.fields_for :definitions do |ff| %>
        <td class="definition_content">
          <%= ff.label :content, "Definition" %>
          <%= ff.text_area :content, :rows => 3 %>
        </td>
        <td class="definition_group">
          <%= ff.label :group_id, "For:" %>
          <%= ff.collection_select :group_id, Group.all, :id, :name %>
        </td>
        <td class="definition_remove">
          <%= ff.check_box :_destroy %>
          <%= ff.label :_destroy, "Remove this definition" %>
        </td>
      <% end %>
      <td class="tags">
        <%= f.label :tags %><br />
        <%= f.text_field :tags %><br />
      </td>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</tr>
-->
testing

app/views/main/admin.html.erb
<h1>Admin Panel</h1>

<% if !@terms.empty? %>
  <h3>Terms</h3>
  <table>
    <tr>
      <th>Name</th>
      <th>Definitions - Content</th>
      <th>Definitions - Group</th>
      <th>Definitions - Remove</th>
      <th>Tags</th>
      <th>Remove?</th>
      <th>Submit Changes</th>
    </tr>
  <% end %>
  <%= render(@terms) || raw('There are no terms in Technobable. Why not ' + link_to('add one', new_term_path) + '?') %>
</table>

<br />
<br />
<br />
<%= link_to 'Home', '/' %>

app/views/main/home.html.erb
<h1>Home</h1>

<%= form_tag '/search', :method => "get" do %>
  <%= label_tag :q, "Search for:" %>
  <%= search_field_tag :q%>
  <%= submit_tag "Search" %>
<% end %>

<br />
<br />
<br />
<%= link_to 'Admin Panel', '/admin' %>

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><br />
    <%= f.fields_for :definitions do |ff| %>
      <%= ff.label :content, "Definition" %><br />
      <%= ff.text_area :content, :rows => 3 %>
      <%= ff.label :group_id, "For:" %>
      <%= ff.collection_select :group_id, Group.all, :id, :name %>
      <%= ff.check_box :_destroy %>
      <%= ff.label :_destroy, "Remove this definition" %>
      <br />
    <% end %>
    <%= f.label :tags %><br />
    <%= f.text_field :tags %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<h1>Listing terms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Tags</th>
    <th></th>
    <th></th>
  </tr>

<% @terms.each do |term| %>
  <tr>
    <td><%= term.name %></td>
    <td><%= term.tags %></td>
    <td><%= link_to 'Show', term %></td>
    <td><%= link_to 'Edit', edit_term_path(term) %></td>
    <td><%= link_to 'Destroy', term, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Term', new_term_path %>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

app/views/terms/search.html.erb
<h1>Search Results</h1>


  <% if @terms.empty? %>
    <p>No results found.</p>
  <% else %>
    <table>
      <tr>
        <th>Name</th>
        <th>Definition</th>
        <th>Tags</th>
        <th></th>
      </tr>
    <% @terms.each do |term| %>
      <tr>
        <td><%= term.name %></td>
        <% term.definitions.each do |definition| %>
          <td><%= definition.content %></td>
        <% end %>
        <td><%= term.tags %></td>
        <td><%= link_to 'Show', term %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= link_to 'Go Back', :controller => :main, :action => :home %>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @term.name %>
  <br />
  <% if !@term.definitions.nil? %>
    <b>Definitions:</b>
    <% @term.definitions.each do |d| %>
      <li><b>For <%= d.group.name.pluralize %>:</b> <%= d.content %></li>
    <% end %>
  <% else %>
    <b>There are no definitions for this term.</b>
  <% end %>
  <b>Tags:</b>
  <%= @term.tags %>
</p>


<%= link_to 'Edit', edit_term_path(@term) %>
<%= link_to 'Back', terms_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :group %><br />
    <%= f.text_field :group %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Group</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.group %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Group:</b>
  <%= @user.group %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>